필수 1, 2, 3구현
the-kingdoms/study-be pull request #2
Opened 2023-06-28 18:18 UTC by youngcch

제일 최근 커밋에 필수문제 1, 2, 3 제출했습니다. 피드백 부탁드립니다. 보너스 구현도 아직 제출은 안 하였으나 하는 중입니다. 초반에 git push하는데 오류가 있어서 commit이 깔끔하지 않은 점 이해 부탁드립니다 :)

2023-06-29 04:06 UTC, DeveloperRyou requested changes
프로젝트를 잘 구성해주셨습니다.
몇가지 개선해야할 점은
1. .metadata폴더 제거하기
2. 깃 커밋을 잘 활용하기
> - spring 프로젝트를 구성시 git commit -m "INIT: 자바 스프링 프로젝트 초기화"
> - HelloController.java 추가시 git commit -m "FEAT: HelloContoller 파일 생성, '/', '/api/test' 접근시 동작 정의"

와 같이 기능별, 구체적으로 작성해 주시면 좋을 것 같습니다!

2023-06-29 04:06 UTC, DeveloperRyou commented on youngcch/.gitignore
yongcch 의 gitignore에서 .metadata 폴더를 넣어도 실제 metadata가 깃에 안올라가지는 않겠죠? 
gitignore 의 위치 변경이 필요해 보입니다.
1. .metadata 삭제 (다른 곳에 보관)
2. git commit
3. .gitignore 위치 변경
4. .metadata 복원
을 진행해서 git 브랜치에서 .metadata 폴더를 날려주세요!

2023-06-29 04:06 UTC, DeveloperRyou commented on youngcch/HelloWorld/mvnw.cmd
mvnw 가 무엇인지 한번 찾아보시고, 어떨때 사용하는건지, 명령어는 어떻게 되는지 알아보세요!
> 알아보신 이후 댓글로 달아주세요

그리고 mvnw대신 gradle을 사용하는 추세라고 알고 있는데, gradle 적용은 어떻게 하는지도 확인해 보세요.
과제에 적용은 안하셔도 됩니다!

2023-06-29 04:06 UTC, DeveloperRyou commented on youngcch/HelloWorld/src/main/java/com/example/demo/controller/HelloController.java
좋습니다! 기본적으로 Controller에서 서버에 동작을 제어해주게 되는데, 이는 MVC패턴에 대해 공부해보시면 자세히 알 수 있습니다.
M (model)
- DB 를 관리
V (view)
- html 을 관리
C (controller)
- 서버의 전반적인 동작 제어

라고 진짜 간단하게는 이렇게 보시면 되는데, 자세하게는 찾아보시면 좋을 것 같아요!

2023-06-29 08:12 UTC, youngcch commented on youngcch/HelloWorld/mvnw.cmd
mvnw는 maven wrapper의 약자로 maven프로젝트를 생성 시 하위 디렉토리에 생성되는 파일이며 프로젝트 관리도구인 Maven을 편리하게 이용하게 해준다(maven은 xml기반의 설정 파일인 pom.xml를 이용하여 프로젝트의 의존성 등 프로그램의 구성을 정의). mvnw는 프로젝트에 maven을 프로젝트에 설치하지 않고도 빌드 도구를 사용할 수 있도록 해주어 따로 설치하거나 환경변수 설정을 하지 않아도 되어 편리하다. 
프로젝트 디렉토리에 있는 mvnw스크립트로 이동하여 mvnw 뒤에 clean(이전 빌드 결과 제거), test(테스트 실행)등을 입력하여 명령어를 실행가능하다.            mvnw를 알아본 후 요약해서 정리해 봤습니다.!

2023-06-29 09:21 UTC, DeveloperRyou commented on youngcch/HelloWorld/mvnw.cmd
네! 일단은 mvnw스크립트로 진행을 하고, 추후에 mvnw이 불편하거나 필요가 있을 때 gradle이 있다는걸 알고 계시면 좋을거 같아요!

2023-06-30 08:44 UTC, youngcch commented on youngcch/HelloWorld/mvnw.cmd
넵 감사합니다!

2023-06-30 09:46 UTC, youngcch commented on youngcch/.gitignore
.metadata삭제하고 다시할당 했습니다!

2023-06-30 19:45 UTC, youngcch commented
bonus도 구현해 봤는데 혹시 따로 pr해야 하나요??

2023-06-30 23:49 UTC, DeveloperRyou approved these changes
수정사항 확인했습니다.

또, Bonus 까지 잘 구현해주신 부분을 확인했습니다. pr 승인합니다.

2023-06-30 23:49 UTC, DeveloperRyou commented on youngcch/HelloWorld/src/main/java/com/example/demo/controller/HelloController.java
> +	}
네 RequestParam을 이용하여 get 방법으로 넘어오는 요청 처리를 어떻게 했는지 확인할 수 있었습니다.

PathVariable과 같은 어노테이션을 이용하면 다음과 같이 주소를 구성할 수도 있습니다
```
@GetMapping("/api/key/{id}")
public string bonus(@PathVariable Long id)
```

이후에는 @RequestMapping뿐만 아니라
@GetMapping, @PutMapping, @PostMapping, @DeleteMapping 등을 활용해 RESTful 하게 api를 구현해봅시다.
https://velog.io/@seokkitdo/Network-REST%EB%9E%80-REST-API%EB%9E%80-RESTful%EC%9D%B4%EB%9E%80

또한 매개변수로는 RequestBody, AuthenticationPrincipal 과 같은 어노테이션도 사용할 수 있으니 알고계시면 좋을 것 같습니다.

2023-06-30 23:50 UTC, merged